Added more configuration options to file, and implemented HASS Tag functionality
rednblkx/HomeKey-ESP32 pull request #22
Opened 2024-02-11 18:21 UTC by Z-pi

Moved and added configuration options to file config.h and replaced mqtt.h with that. Also added MQTT discovery messages to enable tag functionality with Home Assistant. Don't know if it's a good idea but works for my setup so thought can commit it just in case?

2024-02-13 17:34 UTC, kormax commented
I think it's important to send endpoint ID alongside issuer ID, as without that info you know only if a specific person used the lock, and not what device.

Perhaps that was intentional, for cases when you only want to automate based on what person used the lock.

2024-02-13 22:40 UTC, rednblkx requested changes
overall a very nice addition, however, `mqtt.h`/`config.h` will be superseded by the web interface once #20 will be complete, however i will be merging this once everything is resolved so i can port it over to the web interface

2024-02-13 22:40 UTC, rednblkx commented on src/main.cpp
> +  homeSpan.setWifiCredentials(SSID, WIFI_PWD);
think would be better not to hardcode the wifi credentials, instead we can give the option to assign a control pin using `homespan.setControlPin` to enable Homespan's Device Configuration Mode

2024-02-13 22:40 UTC, rednblkx commented on src/main.cpp
> +  homeSpan.begin(Category::Locks, NAME);
this will only set the MDNS display name, the name that would be shown once configured is set on `new Characteristic::Name("NFC Lock")`

2024-02-13 22:40 UTC, rednblkx commented on src/main.cpp
> +      payload["value_template"] = "{{ value_json.issuerId }}";
not sure how HASS Tags work but would it make sense to also announce a tag with the endpoint id? or maybe replace issuerId altogether?

2024-02-13 22:49 UTC, rednblkx reviewed
i didn't include an `mqtt.h` in the repository because i don't like that GitHub or rather just git doesn't have a way to forget about a file for everyone and it would get in the way when doing a `git pull` since it would be a modified file, don't know how many people would pull this repository instead of downloading a zip or even re-cloning i suppose.
I guess we can leave it, it will be gone once the web interface is up.

2024-02-13 23:05 UTC, rednblkx requested changes
create a hass tag for the endpoint id too

2024-02-13 23:05 UTC, rednblkx commented on src/main.cpp
> +      payload["value_template"] = "{{ value_json.issuerId }}";
scratch that, think it's a bit late for me 😬 💤, i think it should actually be included since it would give more automation options.

2024-02-13 23:06 UTC, rednblkx commented
@kormax the endpointId and issuerId is already being published [here](https://github.com/rednblkx/HomeKey-ESP32/blob/5940f35a0b6fa775a4b6851b2f05e8d0a45056a6/src/main.cpp#L186) and yes it should also be exposed via HASS Tags as it can give you more flexibility on automations.

2024-02-17 14:50 UTC, rednblkx approved these changes

2024-02-17 15:06 UTC, merged